featured_tags_categories:
  default: >-
    [{"category":"1","backgroundColor":"#e6f7ff","textColor":"#005580"},{"tag":"discourse","backgroundColor":"#fff0e6","textColor":"#803300"}]
  json_schema: |
    {
      "type": "array",
      "format": "table",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "tag": {
            "type": "string",
            "description": "Filter by tag id"
          }, 
          "category": {
            "type": "string",
            "description": "Filter by category id"
          },
          "backgroundColor": {
            "type": "string",
            "description": "hex color"
          },
          "textColor": {
            "type": "string",
            "description": "hex color"
          }
        },
        "additionalProperties": false
      }
    }

show_on:
  default: homepage
  type: enum
  choices:
    - everywhere
    - top-menu
    - homepage
    - discovery.custom
    - discovery.latest
    - discovery.categories
    - discovery.top
plugin_outlet:
  default: "above-main-container"
