featured_categories:
  type: list
  list_type: category
  default: ""
featured_tags:
  type: list
  list_type: tag
  default: ""
layout:
  type: enum
  default: list
  choices:
    - list
    - cards
    - none
show_on:
  default: homepage
  type: enum
  choices:
    - everywhere
    - top-menu
    - homepage
    - discovery.custom
    - discovery.latest
    - discovery.categories
    - discovery.top
plugin_outlet:
  default: "above-main-container"
featured_tags_categories:
  default: >-
    [{"id":1,"type":"category","backgroundColor":"#fff", "textColor":"#ff"}]
  json_schema: '{
  "type": "array",
  "format": "table",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "The list title"
      },
      "type": {
        "type": "string",
        "description": "Choose the type of list",
        "enum": [
          "latest",
          "hot",
          "top",
          "new",
          "unread"
        ]
      },
      "category": {
        "type": "string",
        "description": "Filter by category id"
      },
      "backgroundColor": {
        "type": "string",
        "description": "Filter by tag name"
      },
      "textColor": {
        "type": "string",
        "description": "Set a CSS class name for custom styles"
      }
    },
    "additionalProperties": false
  }
}'
